### ISSUE TITLE
질문1 : 실습에 어려움을 겪고 있습니다

### ISSUE THREAD

**Issue by rhtjsdud1986** [rhtjsdud1986/AllInOneNote-AION-#2]
유튜브로 강의를 시청하며 동시에 실습을 진행하기에 화면이(글자가) 너무 작아 현재 노트북으로 영상을 틀고 컴퓨터로 실습 진행하는 식으로 다소 불편함이 있습니다,.,.ㅠㅠ 글자 크기를 확대하거나/코드 작성을 완료하신 뒤 확대하여 3초정도 화면에 비추어 주실 수 있으신가요?

**Comment by yuhanappdev** [comment]
피드백 고마워요 :)
다음 영상에는 글자 크기를 더 확대해서 찍도록 할께요
