### ISSUE TITLE
프로젝트  이름 재지정 건의

### ISSUE THREAD

**Issue by yuhanappdev** [rhtjsdud1986/AllInOneNote-AION-#3]
프로젝트의 이름을 GameRecommendApp 이라고 지었는데 
고선영학생이 만들 앱은 올인원다이어리앱이니깐 그에 걸맞는 다른 이름을 지어보면 어떨가요?
![image](https://user-images.githubusercontent.com/63232395/79185506-05ec1f00-7e52-11ea-87cf-7bea04bea292.png)
settings 메뉴에 가면 프로젝트 이름을 변경할 수 있으니 앱의 정체성이 확 드러날 수 있는 멋진 이름을 고민해봐요 :)

**Comment by rhtjsdud1986** [comment]
변경해봤어요. 감사합니다!
