### ISSUE TITLE
질문2 : 기획>개발 도중 수정

### ISSUE THREAD

**Issue by rhtjsdud1986** [rhtjsdud1986/AllInOneNote-AION-#4]
기획에서 결정한 앱은 5/11일 이후 변경이 안된다고 말씀해주셨는데 개발중 앱을 바꾸는 것이 아닌 일부 기능을 수정하는 것은 가능한가요?ㅠㅠ 예상보다 개발 난이도가 높아질 듯하여 걱정되어 여쭈어봅니다...

**Comment by yuhanappdev** [comment]
기능 수정은 5/11 이후에도 가능해요

**Comment by rhtjsdud1986** [comment]
그렇군요! 감사합니다!!
